# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        description: Trims trailing whitespace.
      - id: end-of-file-fixer
        description: Ensures that a file is either empty, or ends with one newline.

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-tabs
        description: Replace tabs by whitespaces before committing
        files: \.(c|h|cc|cpp|hpp|sf)$|CMakeLists.txt|Dockerfile

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.3.0
    hooks:
        - id: commitlint
          description: >
            Commitlint checks if your commit messages meet the conventional commit format.
            In general the pattern mostly looks like: type(scope): [ticket] subject
          stages: [manual]
          additional_dependencies: ['@commitlint/config-conventional']

  - repo: https://github.com/crate-ci/typos
    rev: v1.13.4
    hooks:
        - id: typos
          description: Finds and corrects spelling mistakes among source code.
          exclude: \.git

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.5.1
    hooks:
        - id: markdownlint-cli2
          description: A tool to check markdown files and flag style issues.
          exclude: CHANGELOG.md

## Just adding one line at the end
